# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c849cf535064b32cfce75957d35a0544abcf769c4563c4c0c2720d66be5138319d5ba7b82f6c81866a2d457e786c9619a69a76ffd14015b55ed8ee45145897b4

test:
  secret_key_base: ecf8614ecc1648882c7a4678d14ffda1f10ad1e4c427d331a8081882923a93f6f74743fcd93f194140c8cb34a8985c6b9eb05328c47b49e3fb4309f4c7aee7df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
